### ISSUE TITLE
Hashvault

### ISSUE THREAD

**Issue by MineMoneroPRO** [bobbieltd/nodejs-pool#8]
Hi guys,
My crypto logos and starting page are not opensourced.

Sorry to write this here, but issues on pool ui are closed.

**Comment by bobbieltd** [comment]
Sorry, I don’t know that your logos are made by yourself. For starting page, I agree I’m wrong and I put it on neocities.org. I’ll remove frontpage. For logo, I’m wrong again. I thought you downloaded from Google. I’ll change logo and starting page.

**Comment by bobbieltd** [comment]
semipool.neocites.org : removed
All logos : changed to official logos (I'm not sure yet that I need to ask aeon and electroneum for permissions, I'll google it)
You can check if there is still something that I do wrongly.  Anyway, your pools are great, that is the reason I'm trying to imitate. I close this issue but if there are more concerns, I'll reopen it. I'm sorry for not asking for your permission.

**Comment by bobbieltd** [comment]
I’ve sent my request to Electroneum and Aeon for permissions to use their official logo ( not yours, I won’t use yours as your request ).
![8ee6f4d5-4e25-4974-85c4-b8ffd0b97325](https://user-images.githubusercontent.com/29669374/34703297-c2f68612-f524-11e7-8e26-f1b1cd158488.png)
